app = "imaedge"
primary_region = "fra"

[build]
  dockerfile = "./Dockerfile"

[env]
  PHX_SERVER = "true"
  PHX_HOST = "www.imaedge.org"
  PORT = "8080"
  POOL_SIZE = "5"
  AWS_REGION = "auto"
  TIGRIS_PUBLIC_BASE_URL = "https://imaedge-prod.t3.tigrisfiles.io"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

[deploy]
  strategy = "immediate"
  release_command = "/app/bin/imaedge eval 'Imaedge.Release.migrate'"

[[vm]]
  size = "shared-cpu-1x"
  memory_mb = 512
