import Config

# Configure your database
database_hostname = System.get_env("PGHOST") || "localhost"

database_ssl_options =
  case System.get_env("PGSSLMODE") do
    "verify-full" ->
      root_cert = System.get_env("PGSSLROOTCERT") || "sqlca.pem"

      [
        ssl: [
          verify: :verify_peer,
          cacertfile: Path.expand(root_cert, File.cwd!()),
          server_name_indication: String.to_charlist(database_hostname),
          customize_hostname_check: [
            match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
          ]
        ]
      ]

    "require" ->
      [ssl: [verify: :verify_none]]

    _other ->
      []
  end

config :imaedge, Imaedge.Repo,
  username: System.get_env("PGUSER") || System.get_env("USER") || "postgres",
  password: System.get_env("PGPASSWORD") || "",
  hostname: database_hostname,
  database: System.get_env("PGDATABASE") || "imaedge_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :imaedge, Imaedge.Repo, database_ssl_options

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :imaedge, ImaedgeWeb.Endpoint,
  # Bind to all interfaces so phones on the local network can test the app.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "RIQrGpM2uZjn8CRSGzzJBh7wQ8D1w5/L0DeXiSyZfSClZF5tN2++8NHw6iTYzXx5",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:imaedge, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:imaedge, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :imaedge, ImaedgeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/imaedge_web/router\.ex$"E,
      ~r"lib/imaedge_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :imaedge, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

if System.get_env("BUCKET_NAME") do
  config :imaedge, :object_storage,
    adapter: Imaedge.Storage.Tigris,
    bucket_name: System.get_env("BUCKET_NAME"),
    endpoint: System.get_env("AWS_ENDPOINT_URL_S3") || "https://t3.storage.dev",
    public_base_url: System.get_env("TIGRIS_PUBLIC_BASE_URL")
end
